### PR TITLE
Added a help page and its link buttons to set up GitHub info in user settings page.

### PR DESCRIPTION
**Pull request by hiroshinishio**
## Problem:

I think users would be in trouble to set up GitHub info because there are not help page before.

## Solution:

- Added the help page
- Added the link button to the help page in the user settings page by ? mark icon buttons
- Added the link button to the user settings page by gear icon in dashboard page

## Evidences:

image
image

image

## Caveats:

1. ~The two question mark buttons are slightly misplaced, but I couldn't figure out how to fix it, so I need to fix it in another pull request~
2. Also, when the question mark button is pressed, the help page opens in a separate tab, but the behavior is slow.
3. ~The area circled in red in the screenshot of the help page is handwritten, so it may not look cool. I'd like to get feedback and fix it if necessary.~

Regarding no.2 would be treated in another pull requests.

### CODE REVIEW

**Comment by peeyalk** [comment]
@hiroshinishio 

>`The two question mark buttons are slightly misplaced, but I 
couldn't figure out how to fix it, so I need to fix it in another pull request`
Did you try fixing it in chrome developers tool by assigning css properties directly to the html?

>`Also, when the question mark button is pressed, the help page opens in a separate tab, but the behavior is slow.`
Isn't it because of the image size?

>`The area circled in red in the screenshot of the help page is handwritten, so it may not look cool. I'd like to get feedback and fix it if necessary.`
Yes. They look not so eye catching

**Comment by hiroshinishio** [comment]
> Did you try fixing it in chrome developers tool by assigning css properties directly to the html?

No, I should have tried, I am going to do it next time with you because we want to match them visually together.

**Comment by hiroshinishio** [comment]
@peeyalk 

> Isn't it because of the image size?

Maybe no? because when I removed `target='_blank'`, it was very fast maybe thanks to a next.js feature.

**Comment by hiroshinishio** [comment]
@peeyalk 

> Yes. They look not so eye catching

Thank you for your comments, I totally agree that, I should definitely replace with a cleaner red mark in another pull request, OK?

**Comment by hiroshinishio** [comment]
@peeyalk Re-submitted my pull request, so could you take a look into it?

**Review by peeyalk — APPROVED** [review]

**Pull request merged**
